apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: amma-allow-all
  namespace: amma
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - {}
  egress:
    - {}
