apiVersion: v1
kind: Service
metadata:
  name: amma-gateway
  labels:
    app: amma-gateway
spec:
  type: {{ .Values.service.type }}
  selector:
    app: amma-gateway
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
