apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: amma-gateway
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: amma-gateway
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
