apiVersion: v1
kind: Secret
metadata:
  name: amma-app-secrets
  namespace: amma
type: Opaque
stringData:
  JWT_SECRET_KEY: "dev-secret"
  POSTGRES_PASSWORD: "postgres"
  REDIS_PASSWORD: "redis"
  MINIO_ROOT_USER: "minio"
  MINIO_ROOT_PASSWORD: "minio123"
