apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: amma-gateway
  namespace: amma
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: amma-gateway-vs
  namespace: amma
spec:
  hosts:
    - "*"
  gateways:
    - amma-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: amma-gateway.amma.svc.cluster.local
            port:
              number: 8000
