apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amma-analytics-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: amma-platform
  source:
    repoURL: https://github.com/Med-mhmdi/AMMA-2.git
    targetRevision: main
    path: infra/helm/amma-analytics-service
  destination:
    server: https://kubernetes.default.svc
    namespace: amma
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true


