apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amma-analytics-service
  namespace: argocd
spec:
  project: amma-platform
  source:
    repoURL: https://github.com/amimoh29400/AMMA-2.git
    targetRevision: main
    path: infra/helm/amma-analytics-service
  destination:
    server: https://kubernetes.default.svc
    namespace: amma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

