from datetime import datetime, timezone
from io import BytesIO

from fastapi import APIRouter, File, HTTPException, UploadFile
from minio import Minio
from minio.error import S3Error
from pydantic import BaseModel

from app.config import settings


router = APIRouter(prefix="/storage", tags=["Storage / MinIO"])


def get_minio_client() -> Minio:
    """
    Build MinIO client from environment variables.
    Inside Docker network, the endpoint should be minio:9000.
    """
    endpoint = getattr(settings, "MINIO_ENDPOINT", "minio:9000")
    access_key = getattr(settings, "MINIO_ROOT_USER", "minio")
    secret_key = getattr(settings, "MINIO_ROOT_PASSWORD", "minio123")
    secure = str(getattr(settings, "MINIO_SECURE", "false")).lower() == "true"

    return Minio(
        endpoint,
        access_key=access_key,
        secret_key=secret_key,
        secure=secure,
    )


def ensure_bucket(client: Minio, bucket_name: str) -> None:
    if not client.bucket_exists(bucket_name):
        client.make_bucket(bucket_name)


class DemoReportPayload(BaseModel):
    user_id: int = 1
    title: str = "AMMA Demo Monthly Report"
    content: str | None = None


class DemoSnapshotPayload(BaseModel):
    user_id: int = 1
    month: str = "2026-05"
    total_expenses: float = 0
    top_categories: list[str] = ["Food", "Transport", "Books"]


@router.get("/minio/health")
def minio_health():
    """
    Check MinIO connection and make sure AMMA buckets exist.
    """
    try:
        client = get_minio_client()

        buckets = [
            "amma-receipts",
            "amma-reports",
            "amma-analytics-snapshots",
        ]

        for bucket in buckets:
            ensure_bucket(client, bucket)

        return {
            "status": "ok",
            "service": "minio",
            "buckets": buckets,
        }

    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"MinIO health failed: {exc}")


@router.get("/buckets")
def list_buckets():
    """
    List buckets from MinIO.
    """
    try:
        client = get_minio_client()
        buckets = client.list_buckets()

        return {
            "status": "ok",
            "buckets": [
                {
                    "name": bucket.name,
                    "creation_date": bucket.creation_date.isoformat()
                    if bucket.creation_date
                    else None,
                }
                for bucket in buckets
            ],
        }

    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Could not list buckets: {exc}")


@router.post("/receipts/upload")
async def upload_receipt(file: UploadFile = File(...)):
    """
    Upload a receipt file to MinIO through AMMA Gateway.
    This proves AMMA is using MinIO, not only manual upload.
    """
    try:
        client = get_minio_client()
        bucket_name = "amma-receipts"
        ensure_bucket(client, bucket_name)

        file_bytes = await file.read()
        object_name = (
            f"receipt_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}_"
            f"{file.filename}"
        )

        client.put_object(
            bucket_name,
            object_name,
            BytesIO(file_bytes),
            length=len(file_bytes),
            content_type=file.content_type or "application/octet-stream",
        )

        return {
            "status": "ok",
            "bucket": bucket_name,
            "object_name": object_name,
            "filename": file.filename,
            "size_bytes": len(file_bytes),
        }

    except S3Error as exc:
        raise HTTPException(status_code=500, detail=f"MinIO upload failed: {exc}")
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Receipt upload failed: {exc}")


@router.post("/reports/demo")
def create_demo_report(payload: DemoReportPayload):
    """
    Create a demo financial report file in MinIO.
    This is a real AMMA API -> MinIO storage flow.
    """
    try:
        client = get_minio_client()
        bucket_name = "amma-reports"
        ensure_bucket(client, bucket_name)

        created_at = datetime.now(timezone.utc).isoformat()

        report_content = payload.content or (
            "AMMA Monthly Expense Report\n"
            f"User ID: {payload.user_id}\n"
            f"Title: {payload.title}\n"
            f"Generated at: {created_at}\n\n"
            "This file was generated by AMMA Gateway and stored in MinIO.\n"
            "It demonstrates object storage for exported financial reports.\n"
        )

        data = report_content.encode("utf-8")
        object_name = (
            f"report_user_{payload.user_id}_"
            f"{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.txt"
        )

        client.put_object(
            bucket_name,
            object_name,
            BytesIO(data),
            length=len(data),
            content_type="text/plain",
        )

        return {
            "status": "ok",
            "bucket": bucket_name,
            "object_name": object_name,
            "size_bytes": len(data),
        }

    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Report demo failed: {exc}")


@router.post("/analytics/snapshot/demo")
def create_demo_analytics_snapshot(payload: DemoSnapshotPayload):
    """
    Create a demo analytics snapshot JSON file in MinIO.
    """
    try:
        import json

        client = get_minio_client()
        bucket_name = "amma-analytics-snapshots"
        ensure_bucket(client, bucket_name)

        snapshot = {
            "user_id": payload.user_id,
            "month": payload.month,
            "total_expenses": payload.total_expenses,
            "top_categories": payload.top_categories,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "source": "AMMA Analytics Snapshot Demo",
        }

        data = json.dumps(snapshot, indent=2).encode("utf-8")
        object_name = (
            f"analytics_snapshot_user_{payload.user_id}_"
            f"{payload.month}_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}.json"
        )

        client.put_object(
            bucket_name,
            object_name,
            BytesIO(data),
            length=len(data),
            content_type="application/json",
        )

        return {
            "status": "ok",
            "bucket": bucket_name,
            "object_name": object_name,
            "snapshot": snapshot,
        }

    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Snapshot demo failed: {exc}")
